# -*- coding: utf-8 -*-
"""DogDetectionBlynkDashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdmHhnl0f1xIpPUooS4Rf-CV9UqclYBt
"""

# Install dependencies
!pip install ultralytics opencv-python-headless
!sudo apt-get install -y libgl1

import os
from ultralytics import YOLO
import cv2
import requests
from datetime import datetime, timezone
import pytz
from google.colab import drive
import time
from urllib.parse import quote
import pandas as pd

# ================== TIMEZONE CONFIGURATION ==================
# Set your desired timezone (e.g., 'America/New_York', 'Asia/Singapore')
YOUR_TIMEZONE = 'Asia/Singapore'
timezone = pytz.timezone(YOUR_TIMEZONE)

# ================== CONFIGURATION ==================
# Blynk Settings
BLYNK_AUTH_TOKEN = "uEnVOzsWof-pQaHzKwHv4HSxkOZJRqsp"
V_DOGS_CURRENT = 'V0'     # Current dogs in frame (integer)
V_CONFIDENCE = 'V1'      # Confidence value (float, 0.0 when no dog)
V_DETECTION_STATUS = 'V2' # "Dog Detected" or "No Dog" (string)
V_TIMESTAMP = 'V3'        # Timestamp (string)
V_LOCATION = 'V5'        # Street location (string)

# Location Mapping (customize these coordinates)
LOCATION_MAPPING = {
    (0, 300): "Main Street",    # Left side of frame
    (300, 640): "Park Avenue"   # Right side of frame
}

# Detection Parameters
FRAME_SKIP = 15           # Process every 15th frame
MIN_CONFIDENCE = 0.82     # Minimum confidence to count as detection
MIN_DETECTION_GAP = 1.0   # Seconds between counting the same dog

# ================== HELPER FUNCTIONS ==================
def get_location(x_center):
    """Convert x-coordinate to street name."""
    for (x_min, x_max), location in LOCATION_MAPPING.items():
        if x_min <= x_center < x_max:
            return location
    return "Unknown Area"

def blynk_update(pin, value):
    """Send data to Blynk."""
    try:
        url = f"https://blynk.cloud/external/api/update?token={BLYNK_AUTH_TOKEN}&{pin}={quote(str(value))}"
        return requests.get(url, timeout=3).status_code == 200
    except:
        return False

def blynk_notify(message):
    """Send Blynk notification."""
    try:
        url = f"https://blynk.cloud/external/api/notify?token={BLYNK_AUTH_TOKEN}&message={quote(message)}"
        return requests.get(url).status_code == 200
    except:
        return False

def get_current_timestamp():
    """Get current timestamp in the correct timezone."""
    return datetime.now(timezone).strftime("%Y-%m-%d (%H:%M:%S)")

# ================== INITIALIZATION ==================
# Verify timezone setup
print("="*50)
print(f"Timezone verification:\nLocal time: {datetime.now()}\nUTC time: {datetime.utcnow()}\n{timezone} time: {datetime.now(timezone)}")
print("="*50)

# Mount Google Drive
try:
    drive.mount('/content/drive')
except:
    print("Drive already mounted")

# Load YOLO model
model = YOLO('/content/best (1).pt')  # Update path to your model
input_video = '/content/drive/My Drive/Imaging System/DogVideo2.mp4'
cap = cv2.VideoCapture(input_video)

# Video writer setup
video_name = os.path.splitext(os.path.basename(input_video))[0]
output_video_path = f'/content/drive/My Drive/detections/{video_name}_annotated.mp4'
fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

# Detection log (now includes location)
detection_log = pd.DataFrame(columns=['timestamp', 'current_count', 'location', 'confidence'])
log_file = "/content/drive/My Drive/detections/detection_log.csv"

# ================== MAIN DETECTION LOOP ==================
def run_detection():
    global detection_log

    # Initialize tracking variables
    start_time = time.time()
    last_notify_time = 0
    last_detections = {}  # Tracks individual dogs to avoid double-counting

    # Initial 5-second idle state (no dogs)
    while time.time() - start_time < 5:
        blynk_update(V_DETECTION_STATUS, "No Dog")
        blynk_update(V_DOGS_CURRENT, 0)
        blynk_update(V_LOCATION, "No Detection")
        blynk_update(V_CONFIDENCE, 0.0)  # Explicit 0.0 float
        time.sleep(0.1)

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        current_time = time.time()
        timestamp = get_current_timestamp()
        annotated_frame = frame.copy()

        # Process every FRAME_SKIP-th frame
        if int(cap.get(cv2.CAP_PROP_POS_FRAMES)) % FRAME_SKIP == 0:
            results = model(frame, imgsz=640, conf=0.5, iou=0.5)
            dog_detected = False
            max_confidence = 0.0  # Initialize as float
            current_dog_count = 0
            current_location = "No Detection"

            for box in results[0].boxes:
                if model.names[int(box.cls[0])].lower() == "dog":
                    confidence = float(box.conf[0])
                    max_confidence = max(max_confidence, confidence)

                    if confidence >= MIN_CONFIDENCE:
                        dog_detected = True
                        x_center = int((box.xyxy[0][0] + box.xyxy[0][2]) / 2)
                        y_center = int((box.xyxy[0][1] + box.xyxy[0][3]) / 2)
                        dog_id = f"{x_center}_{y_center}"

                        # Get location and update current_location
                        location = get_location(x_center)
                        current_location = location if current_location == "No Detection" else "Multiple Areas"

                        # Draw bounding box with location
                        x1, y1, x2, y2 = map(int, box.xyxy[0])
                        cv2.rectangle(annotated_frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                        cv2.putText(annotated_frame, f"{location} {confidence:.2f}",
                                    (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

                        current_dog_count += 1

                        # Avoid double-counting the same dog within MIN_DETECTION_GAP seconds
                        if current_time - last_detections.get(dog_id, 0) > MIN_DETECTION_GAP:
                            last_detections[dog_id] = current_time

            # Update Blynk (critical confidence fix here)
            if dog_detected:
                blynk_update(V_DETECTION_STATUS, "Dog Detected")
                blynk_update(V_DOGS_CURRENT, current_dog_count)
                blynk_update(V_LOCATION, current_location)
                blynk_update(V_CONFIDENCE, float(max_confidence))  # Force float
                blynk_update(V_TIMESTAMP, timestamp)

                # Notify every 30 seconds max
                if current_time - last_notify_time > 30:
                    blynk_notify(f"Dog on {current_location} (Conf: {max_confidence:.2f})")
                    last_notify_time = current_time
            else:
                blynk_update(V_DETECTION_STATUS, "No Dog")
                blynk_update(V_DOGS_CURRENT, 0)
                blynk_update(V_LOCATION, "No Detection")
                blynk_update(V_CONFIDENCE, 0.0)  # Explicit 0.0 for no detection

            # Log the detection (ensures 0.0 when no dog)
            detection_log.loc[len(detection_log)] = {
                'timestamp': timestamp,
                'current_count': current_dog_count,
                'location': current_location,
                'confidence': max_confidence if dog_detected else 0.0  # Force 0.0
            }

            # Write frame to local video (no Blynk upload)
            out.write(annotated_frame)
            time.sleep(0.05)  # Prevents overloading CPU

    # Final cleanup (5 seconds of "no detection" state)
    for _ in range(10):
        blynk_update(V_DETECTION_STATUS, "No Dog")
        blynk_update(V_DOGS_CURRENT, 0)
        blynk_update(V_LOCATION, "No Detection")
        blynk_update(V_CONFIDENCE, 0.0)
        time.sleep(0.5)

    # Release resources
    out.release()
    detection_log.to_csv(log_file, index=False)
    print(f"Annotated video saved to: {output_video_path}")
    print("Final timestamp verification:", get_current_timestamp())

# ================== RUN DETECTION ==================
run_detection()